name: dopt-experiments

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  update:
    if: ${{ contains(github.event.head_commit.message, '[run]') }}
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - julia-version: '1.8'
            os: ubuntu-latest
            arch: x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@v1
      - name: Setup Git
        run: |
          git config --global user.name  "GitHub Action"
          git config --global user.email "action@github.com"
      - name: Run Jobs
        run: julia --proj ./scripts/run_experiments.jl
        env:
          DOPT_AUTHOR: ${{ github.actor }}
      - name: Save Results
        run: |
          git checkout results || git checkout -b results
          git add -f ./data/results/job-*
          git commit -m "Update Results [actions]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
